### ISSUE TITLE
Copilot instructions

### ISSUE THREAD

**Issue by kmarekspartz** [kmarekspartz/mediawiki-agent#1]
To scaffold your repository (kmarekspartz/mediawiki-agent) as a Python project with smolagents and pywikibot dependencies, and to set it up for building smolagent Tools for interacting with MediaWiki instances, here are the recommended steps:

### 1. Set Up Project Structure

Create the following directory structure:
```plaintext
mediawiki-agent/
├── mediawiki_agent/
│   ├── __init__.py
│   └── tools.py
├── tests/
│   └── test_tools.py
├── pyproject.toml
├── README.md
└── .gitignore
```

### 2. Create `pyproject.toml` for Dependencies

Here’s a starter `pyproject.toml` using [Hatchling](https://hatch.pypa.io/latest/) (or you can use Poetry or setuptools):

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mediawiki-agent"
version = "0.1.0"
description = "smolagent Tools for interacting with MediaWiki instances"
authors = [{name = "kmarekspartz"}]
dependencies = [
    "smolagents",
    "pywikibot"
]

[tool.hatch.build.targets.sdist]
exclude = ["/tests"]
```

### 3. Example Tool Implementation

Create `mediawiki_agent/tools.py`:

```python
import pywikibot
from smolagents.tools import Tool

class GetPageContentTool(Tool):
    name = "get_page_content"
    description = "Gets the content of a MediaWiki page."

    def __init__(self, site_url):
        super().__init__()
        self.site = pywikibot.Site(url=site_url)

    def run(self, page_title: str) -> str:
        page = pywikibot.Page(self.site, page_title)
        return page.text

# Additional tools can be added similarly.
```

### 4. Example Test File

Create `tests/test_tools.py`:

```python
def test_get_page_content_tool():
    # Example test; in practice, use a test or mock wiki instance
    assert True
```

### 5. .gitignore

Include standard Python ignores:

```
__pycache__/
*.pyc
.env
.venv
```

### 6. Install Dependencies Locally

Run:
```bash
pip install smolagents pywikibot
```

---

## Next Steps

Would you like code for more example tools, or guidance on how to package and distribute this project? If you want, I can generate the exact code for the scaffolding files above. Let me know how hands-on you want the setup to be!
